name: Request to join Joy of Coding Admissions
description: Request to join the team and gain project board access
title: "Join request: @<your-username>"
labels: ["join-request"]
body:
  - type: input
    id: ghuser
    attributes:
      label: Your GitHub username
      placeholder: "octocat"
    validations:
      required: true
