name: Request to join Mod 2
description: Request to join the organization team with access to the project board
title: "Join request: @<your-username>"
labels: ["join-request"]
body:
  - type: markdown
    attributes:
      value: |
        **Welcome!**  
        Please fill out this short form to request access to our organization.  
        ⚠️ **Note:** This issue is public — only share your GitHub username.
        You’ll receive an invite automatically once approved.

  - type: input
    id: ghuser
    attributes:
      label: Your GitHub username
      description: "Example: octocat (no @)"
      placeholder: "octocat"
    validations:
      required: true

