name: Auto-join AdmissionsTeam
on:
  issues:
    types: [opened, labeled]

permissions:
  issues: write

jobs:
  join:
    if: |
      github.event.action == 'opened' || 
      (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'join-request'))
    runs-on: ubuntu-latest
    steps:
      - name: Ensure required secrets
        run: |
          test -n "${{ secrets.ORG }}" && test -n "${{ secrets.TEAM_SLUG }}" || { echo "Missing ORG or TEAM_SLUG"; exit 1; }

      # If using a GitHub App (recommended), create an installation token first:
      - name: Generate GitHub App installation token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ secrets.ORG }}

      - name: Extract form inputs
        id: parse
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const body = context.payload.issue.body || "";
            const uMatch = body.match(/ghuser.*\n.*value:\s*"?([A-Za-z0-9-]+)"?/);
            const eMatch = body.match(/email.*\n.*value:\s*"?([^"\n]+)"?/);
            const username = uMatch ? uMatch[1].trim() : null;
            const email = eMatch ? eMatch[1].trim() : null;
            if (!username) {
              core.setFailed("No GitHub username provided.");
            }
            core.setOutput('username', username);
            core.setOutput('email', email || '');

      - name: Check if user is already in org
        id: check-member
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const org = process.env.ORG;
            const username = '${{ steps.parse.outputs.username }}';
            try {
              await github.request('GET /orgs/{org}/members/{username}', { org, username });
              core.setOutput('isMember', 'true'); // 204 means member
            } catch (e) {
              core.setOutput('isMember', 'false'); // 404 not a member
            }
        env:
          ORG: ${{ secrets.ORG }}

      - name: Invite to org if needed
        if: steps.check-member.outputs.isMember == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const org = process.env.ORG;
            const username = '${{ steps.parse.outputs.username }}';
            const email = '${{ steps.parse.outputs.email }}';
            // Get user id if we have a username
            let invitee_id = null;
            if (username) {
              const user = await github.request('GET /users/{username}', { username });
              invitee_id = user.data.id;
            }
            // Create org invitation
            await github.request('POST /orgs/{org}/invitations', {
              org,
              invitee_id, // prefer ID
              email: email || undefined
            });
        env:
          ORG: ${{ secrets.ORG }}

      - name: Add/update team membership
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const org = process.env.ORG;
            const team_slug = process.env.TEAM_SLUG;
            const username = '${{ steps.parse.outputs.username }}';
            // This works even if the user is pending org invitation; they'll land in "pending" until they accept
            await github.request('PUT /orgs/{org}/teams/{team_slug}/memberships/{username}', {
              org, team_slug, username,
              role: 'member'
            });
        env:
          ORG: ${{ secrets.ORG }}
          TEAM_SLUG: ${{ secrets.TEAM_SLUG }}

      - name: Comment status
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const username = '${{ steps.parse.outputs.username }}';
            const isMember = '${{ steps.check-member.outputs.isMember }}' === 'true';
            const note = isMember
              ? `✅ @${username} is in the org. Added/updated their membership in **${process.env.TEAM_SLUG}**.`
              : `✉️ Invited @${username} to the org and added them to **${process.env.TEAM_SLUG}** (will activate after they accept).`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: note
            });
        env:
          TEAM_SLUG: ${{ secrets.TEAM_SLUG }}
